// Generated by GenerateCppCodeHardFunction.m on Mon 15 Oct 2018 10:50:50

#ifndef __HARD_H_
#define __HARD_H__

#include <heplib/MathematicaC.hh>
#include "common.hh"

void hardqq0 (double M, double theta, double mt, double mu, double hardmatrix[2][2]); 

void hardqq1 (double M, double theta, double mt, double mu, double hardmatrix[2][2]); 

void hardgg0 (double M, double theta, double mt, double mu, double hardmatrix[3][3]); 

void hardgg1 (double M, double theta, double mt, double mu, double hardmatrix[3][3]); 

#endif/*__HARD_H__*/
