// Generated by GenerateCppCodeSoftFunction.m on Mon 15 Oct 2018 10:53:33

#ifndef __SOFT_H_
#define __SOFT_H__

#include <heplib/MathematicaC.hh>
#include "common.hh"

void softqq00 (double M, double theta, double mt, double softmatrix[2][2]); 

void softqq11 (double M, double theta, double mt, double softmatrix[2][2]); 

void softqq10 (double M, double theta, double mt, double softmatrix[2][2]); 

void softqq22 (double M, double theta, double mt, double softmatrix[2][2]); 

void softqq21 (double M, double theta, double mt, double softmatrix[2][2]); 

void softgg00 (double M, double theta, double mt, double softmatrix[3][3]); 

void softgg11 (double M, double theta, double mt, double softmatrix[3][3]); 

void softgg10 (double M, double theta, double mt, double softmatrix[3][3]); 

void softgg22 (double M, double theta, double mt, double softmatrix[3][3]); 

void softgg21 (double M, double theta, double mt, double softmatrix[3][3]); 

#endif/*__SOFT_H__*/
